spring:
  config:
    import: file:.env[.properties]
  datasource:
    url: ${DB_URL}
    driverClassName: org.h2.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  h2:
    console:
      enabled: true
  application:
    name: iran-gold-tracker
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
brs:
  api:
    key: ${BRS_API_KEY}
    base-url: ${BRS_API_URL}

telegram:
  bot:
    token: ${BOT_TOKEN}